In [8]:
import numpy as np


def longest_seq(x):
    s_max, s = 0, 0
    for i in x:
        s = s+1 if i else 0
        if s > s_max:
            s_max = s
    return s_max


def oyun(n=250):
    x = np.random.randint(0, 2, n)
    m = longest_seq(x)
    return x, m

In [12]:
# Sanity check
for _ in range(4):
    print(oyun(20))

(array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0]), 8)
(array([0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1]), 3)
(array([1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1]), 4)
(array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1]), 3)


In [15]:
N_TRIALS = 10**6
s = 0
for _ in range(N_TRIALS):
    x, m = oyun()
    s += m
print(s/N_TRIALS)

3.730606
